"""Initial migration.

Revision ID: 66f56a772727
Revises: 
Create Date: 2023-10-12 19:49:34.997765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f56a772727'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creatorname', sa.String(length=150), nullable=False),
    sa.Column('creatoremail', sa.String(length=150), nullable=False),
    sa.Column('eventname', sa.String(length=150), nullable=False),
    sa.Column('polldescription', sa.String(length=500), nullable=True),
    sa.Column('shareresults', sa.Boolean(), nullable=False),
    sa.Column('eventdate', sa.DateTime(), nullable=True),
    sa.Column('datecreated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inviteename', sa.String(length=150), nullable=False),
    sa.Column('inviteeemail', sa.String(length=150), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questiondate', sa.String(length=150), nullable=False),
    sa.Column('questiontime', sa.String(length=150), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Boolean(), nullable=False),
    sa.Column('questions_id', sa.Integer(), nullable=False),
    sa.Column('invitees_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invitees_id'], ['invitees.id'], ),
    sa.ForeignKeyConstraint(['questions_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_answers')
    op.drop_table('questions')
    op.drop_table('invitees')
    op.drop_table('event')
    # ### end Alembic commands ###
